# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
predictCpp2 <- function(xData, yData, xPred) {
    .Call('_polijus_predictCpp2', PACKAGE = 'polijus', xData, yData, xPred)
}

