# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Interpolador/extrpolador linear
#'
#' Função para interpolar ou extrapolar linearmente em um conjunto de dados
#'
#' @param xData absissas dos dados
#' @param yData ordenadas dos dados
#' @param xPred absissas para interpolar/extrapolar
#' @param nExtrap número de observações utilizadas para extrapolação
#'
#' @return vetor numérico de dados interpolados/extrapolados
#'
#' @export
#'
predictCpp2 <- function(xData, yData, xPred, nExtrap = 2L) {
    .Call('_polijus_predictCpp2', PACKAGE = 'polijus', xData, yData, xPred, nExtrap)
}

